# Generated by Django 3.0.5 on 2020-05-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='specialty',
            field=models.CharField(max_length=40),
        ),
    ]
