# Generated by Django 3.0.5 on 2020-05-09 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20200504_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
