# Generated by Django 3.0.5 on 2020-05-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20200521_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='floor',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.ManyToManyField(related_name='group', to='group.Classroom'),
        ),
    ]
