# Generated by Django 3.0.5 on 2020-05-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20200521_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group',
            new_name='classroom',
        ),
    ]
