# Generated by Django 3.0.5 on 2020-05-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200508_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
