# Generated by Django 3.0.5 on 2020-05-04 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200503_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='employment_date',
            field=models.DateField(default=datetime.date(2020, 5, 4)),
        ),
    ]
