# Generated by Django 3.0.5 on 2020-05-08 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200504_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='employment_date',
            field=models.DateField(default=datetime.date(2020, 5, 8)),
        ),
    ]
