# Generated by Django 3.0.5 on 2020-05-09 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20200509_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='employment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
